baseurl      = "https://dcron.in"
title        = "Daniel Cronin"
languageCode = "en-us"
theme        = "hello-friend-ng"
pagination.pagerSize     = 10

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  [params.author]
    name = "Daniel Cronin"


  # Custom footer
  # If you want, you can easily override the default footer with your own content.
  #
  [params.footer]
    trademark = 2024
    rss = true
    author = true


    bottomText = ['<a href="https://github.com/dcronin05"><img src="https://jandee.vercel.app/dcronin05?scheme=dark" /></a>']

  [[params.social]]
    name = "email"
    url  = "mailto:daniel@dcron.in"

  [[params.social]]
    name = "mastodon"
    url  = "https://mastodon.cronin.one/"

  [[params.social]]
    name = "github"
    url  = "https://github.com/dcronin05"

  [[params.social]]
    name = "gitea"
    url  = "https://git.dcron.in"

  [[params.social]]
    name = "discord"
    url  = "https://discord.com/users/161254752997343232"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Daniel Cronin"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.en.params]
    subtitle  = "dcron.in"

    [languages.en.params.logo]
      logoText = "dcron.in"
      logoHomeLink = "/"
    # or
    #
#     path = "web-app-manifest-192x192.png"
#     alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "hosted"
    name       = "Hosted"
    url        = "/apps"

  [[menu.main]]
    identifier = "mastodon"
    name       = "Mastodon"
    url        = "/mastodon"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"